### ISSUE TITLE
DNS Polluted

### ISSUE THREAD

**Issue by iRemark** [XWJACK/iShadowsocksR#2]
Instagram.app for iOS cannot load picture.  The log show 'DNS Polluted. PROXY'.    How can I resolve it ?   Thanks .

**Comment by XWJACK** [comment]
First, config url rule set for `Potatso`. You can import config from url.

![IMG_1151](https://user-images.githubusercontent.com/15156226/58306404-f9bc3500-7e2d-11e9-85d9-94e40c43fbec.PNG)

URL: [PotatsoConfig](https://github.com/XWJACK/PotatsoConfig) which convert from [Shadowrocket-ADBlock-Rules](https://github.com/h2y/Shadowrocket-ADBlock-Rules)

![IMG_1150](https://user-images.githubusercontent.com/15156226/58306386-ef01a000-7e2d-11e9-9832-ed064a3c3a19.PNG)

**Comment by iRemark** [comment]
https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_top500_banlist_ad.conf
像上面的一条，总是提示 无法保存配置。
![325464B164665BBD408103FD9E68A6C9](https://user-images.githubusercontent.com/12713866/58699519-44aaef00-83d0-11e9-81ac-ffc7f13da26f.png)

**Comment by XWJACK** [comment]
这个是shadowrocket专用的配置，potatso的配置是要转换的，你可以用这里面的https://github.com/XWJACK/PotatsoConfig/tree/master/potatso
